cookietemple_version: '1.3.10 # <<COOKIETEMPLE_NO_BUMP>>'
domain: cli
language: python
project_slug: package-locator
project_slug_no_hyphen: package_locator
template_version: '2.0.1 # <<COOKIETEMPLE_NO_BUMP>>'
template_handle: cli-python
github_username: nasifimtiazohi
creator_github_username: nasifimtiazohi
is_github_repo: true
is_repo_private: false
is_github_orga: false
full_name: Nasif Imtiaz
email: nasifimtiaz88@gmail.com
project_name: package-locator
project_short_description: For a package, locate its source repository url and its
  relative path within the repository
version: 0.4.4
license: MIT
